# -*- coding: utf-8 -*-
"""Group6-FinalProject-DataExtraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pcJWx1ebTl47qW8-dYKY753q6-5idMHz
"""

# Import libraries

import csv
import pandas as pd
import plotly.express as px

print("GROUP 6 PROJECT PYTHON FILE")
print()
print("----------------------------")

# Create file handlers to open and read from csv files
fh = open("Texas Race Data.csv")
fh2 = open("California Race Data.csv")
fh3 = open('California House Information Data.csv')
fh4 = open('Texas House Information.csv')
fh5 = open("Consensus_Data_California_2022.csv")
fh6 = open("Consensus_Data_Texas_2022.csv")

# Read from CSV files
texasData = list(csv.reader(fh6))
caliData = list(csv.reader(fh5))
texasRaceData = list(csv.reader(fh))
caliRaceData = list(csv.reader(fh2))
texasHouseData = list(csv.reader(fh4))
caliHouseData = list(csv.reader(fh3))


# Clean column headers for data
columnHeadersTexas = texasData[0]
columnHeadersTexas[0] = columnHeadersTexas[0].split("\ufeff")
columnHeadersTexas[0] = columnHeadersTexas[0][1]

columnHeadersTexas = texasRaceData[0]
columnHeadersTexas[0] = columnHeadersTexas[0].split("\ufeff")
columnHeadersTexas[0] = columnHeadersTexas[0][1]

columnHeadersCali = caliData[0]
columnHeadersCali[0] = columnHeadersCali[0].split("\ufeff")
columnHeadersCali[0] = columnHeadersCali[0][1]

columnHeadersCali = caliRaceData[0]
columnHeadersCali[0] = columnHeadersCali[0].split("\ufeff")
columnHeadersCali[0] = columnHeadersCali[0][1]

# Create column headers for DataFrames
columnHeaders2 = ['Label (grouping)', 'Owner Morgage Estimate', 'Owner Morgage MoE', 'Percent Morgage Estimate', 'Percent Morgage MoE']
columnHeadersPractice2 = ['1', '2', '3', '4', '5']
columnHeaders = ['Label (grouping)', 'Occupied Housing Units', 'Owner Morgage MoE', 'Percent Morgage Estimate', 'Percent Morgage MoE']
columnHeadersPractice = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']

# Create list for Texas data from the CSV race file
combinedListsTexasRace = []
for i in range(1, len(texasRaceData)):
  tempList = []
  texasRaceData[i][0] = texasRaceData[i][0].split("\xa0")
  for x in range(0, len(texasRaceData[i][0])):
    if not(texasRaceData[i][0][x] == "\xa0" or texasRaceData[i][0][x] == ""):
      tempList.append(texasRaceData[i][0][x])
  for z in range(1, len(texasRaceData[i])):
    if("%" in texasRaceData[i][z]):
      texasRaceData[i][z] = texasRaceData[i][z].split("%")
      for t in range(0, len(texasRaceData[i][z])):
        if not(texasRaceData[i][z][t] == "%"):
          texasRaceData[i][z] = texasRaceData[i][z][t]
          break
    elif("±" in texasRaceData[i][z]):
      texasRaceData[i][z] = texasRaceData[i][z].split("±")
    tempList.append(texasRaceData[i][z])
  combinedListsTexasRace.append(tempList)

df_texasRace = pd.DataFrame(combinedListsTexasRace, columns = columnHeadersPractice)

# Create the DataFrame for Texas data of housing aspects
combinedListsTexas = []
for i in range(1, len(texasData)):
  tempList = []
  texasData[i][0] = texasData[i][0].split("\xa0")
  for x in range(0, len(texasData[i][0])):
    if not(texasData[i][0][x] == "\xa0" or texasData[i][0][x] == ""):
      tempList.append(texasData[i][0][x])
  for z in range(1, len(texasData[i])):
    if("%" in texasData[i][z]):
      texasData[i][z] = texasData[i][z].split("%")
      for t in range(0, len(texasData[i][z])):
        if not(texasData[i][z][t] == "%"):
          texasData[i][z] = texasData[i][z][t]
          break
    elif("±" in texasData[i][z]):
      texasData[i][z] = texasData[i][z].split("±")
    tempList.append(texasData[i][z])
  combinedListsTexas.append(tempList)

df_texas = pd.DataFrame(combinedListsTexas, columns = columnHeadersPractice2)

# Create DataFrame for california Data

combinedListsCali = []
for i in range(1, len(caliData)):
  tempList = []
  caliData[i][0] = caliData[i][0].split("\xa0")
  for x in range(0, len(caliData[i][0])):
    if not(caliData[i][0][x] == "\xa0" or caliData[i][0][x] == ""):
      tempList.append(caliData[i][0][x])
  for z in range(1, len(caliData[i])):
    if("%" in caliData[i][z]):
      caliData[i][z] = caliData[i][z].split("%")
      for t in range(0, len(caliData[i][z])):
        if not(caliData[i][z][t] == "%"):
          caliData[i][z] = caliData[i][z][t]
          break
    elif("±" in caliData[i][z]):
      caliData[i][z] = caliData[i][z].split("±")
    tempList.append(caliData[i][z])
  combinedListsCali.append(tempList)

df_cali = pd.DataFrame(combinedListsCali, columns = columnHeadersPractice2)
combinedListsCaliRace = []

# Create DataFrame for California Race Data

for i in range(1, len(caliRaceData)):
  tempList = []
  caliRaceData[i][0] = caliRaceData[i][0].split("\xa0")
  for x in range(0, len(caliRaceData[i][0])):
    if not(caliRaceData[i][0][x] == "\xa0" or caliRaceData[i][0][x] == ""):
      tempList.append(caliRaceData[i][0][x])
  for z in range(1, len(caliRaceData[i])):
    if("%" in caliRaceData[i][z]):
      caliRaceData[i][z] = caliRaceData[i][z].split("%")
      for t in range(0, len(caliRaceData[i][z])):
        if not(caliRaceData[i][z][t] == "%"):
          caliRaceData[i][z] = caliRaceData[i][z][t]
          break
    elif("±" in caliRaceData[i][z]):
      caliRaceData[i][z] = caliRaceData[i][z].split("±")
    tempList.append(caliRaceData[i][z])
  combinedListsCaliRace.append(tempList)

df_californiaRace = pd.DataFrame(combinedListsCaliRace, columns = columnHeadersPractice)

# Create DataFrame for California housing data

combinedListsCaliHouse = []
for i in range(1, len(caliHouseData)):
  tempList = []
  caliHouseData[i][0] = caliHouseData[i][0].split("\xa0")
  for x in range(0, len(caliHouseData[i][0])):
    if not(caliHouseData[i][0][x] == "\xa0" or caliHouseData[i][0][x] == ""):
      tempList.append(caliHouseData[i][0][x])
  for z in range(1, len(caliHouseData[i])):
    if("%" in caliHouseData[i][z]):
      caliHouseData[i][z] = caliHouseData[i][z].split("%")
      for t in range(0, len(caliHouseData[i][z])):
        if not(caliHouseData[i][z][t] == "%"):
          caliHouseData[i][z] = caliHouseData[i][z][t]
          break
    elif("±" in caliHouseData[i][z]):
      caliHouseData[i][z] = caliHouseData[i][z].split("±")
    tempList.append(caliHouseData[i][z])
  combinedListsCaliHouse.append(tempList)
df_californiaHouse = pd.DataFrame(combinedListsCaliHouse, columns = columnHeadersPractice)

# Create DataFrame for Texas Housing Data

combinedListsTexasHouse = []
for i in range(1, len(texasHouseData)):
  tempList = []
  texasHouseData[i][0] = texasHouseData[i][0].split("\xa0")
  for x in range(0, len(texasHouseData[i][0])):
    if not(texasHouseData[i][0][x] == "\xa0" or texasHouseData[i][0][x] == ""):
      tempList.append(texasHouseData[i][0][x])
  for z in range(1, len(texasHouseData[i])):
    if("%" in texasHouseData[i][z]):
      texasHouseData[i][z] = texasHouseData[i][z].split("%")
      for t in range(0, len(texasHouseData[i][z])):
        if not(texasHouseData[i][z][t] == "%"):
          texasHouseData[i][z] = texasHouseData[i][z][t]
          break
    elif("±" in texasHouseData[i][z]):
      texasHouseData[i][z] = texasHouseData[i][z].split("±")
    tempList.append(texasHouseData[i][z])
  combinedListsTexasHouse.append(tempList)
df_texasHouse = pd.DataFrame(combinedListsTexasHouse, columns = columnHeadersPractice)

# Bar Chart for Year Built from Housing Data

housingCaliYearBuilt_df = df_californiaHouse.iloc[10:17, 0:2]
for i in range(10, len(housingCaliYearBuilt_df) + 10):
  if("," in housingCaliYearBuilt_df["2"][i]):
    housingCaliYearBuilt_df["2"][i] = housingCaliYearBuilt_df["2"][i].replace(",", "")
    housingCaliYearBuilt_df["2"][i] = float(housingCaliYearBuilt_df["2"][i])
housingTexasYearBuilt_df = df_texasHouse.iloc[10:17, 0:2]
for i in range(10, len(housingTexasYearBuilt_df) + 10):
  if("," in housingTexasYearBuilt_df["2"][i]):
    housingTexasYearBuilt_df["2"][i] = housingTexasYearBuilt_df["2"][i].replace(",", "")
    housingTexasYearBuilt_df["2"][i] = float(housingTexasYearBuilt_df["2"][i])
housingCaliYearBuilt_df['State'] = 'California'
housingTexasYearBuilt_df['State'] = 'Texas'
yearBuilt = [housingCaliYearBuilt_df, housingTexasYearBuilt_df]
combinedYearBuilt_df = pd.concat(yearBuilt)
yearBuiltBar = px.bar(combinedYearBuilt_df, x = '1', y = '2', color = 'State', barmode = 'group', labels = {'1':'Year range for Houses Built', '2':'Number of Houses'}, title = 'Number of Houses Built in a Specified Time Frame (California/Texas)')
print("Bar Chart for Range of Years Houses were Built In")
print()
yearBuiltBar.show()
print("Insights: ")
print("1. Texas constructed most of their houses within the 1980-1999 range while California constructed most of their houses within the 1960-1979 range.")
print("2. California overall has constructed more houses than Texas.")
print("3. California built more houses than Texas from earlier than 1939 to 1999.")
print("4. Texas built more houses than California from 2000 to 2020 and later.")
print("5. The number of houses built within both California and Texas started to decrease from 1980 to 2020 and later.")
print(" ")

# Bar Chart for Rooms from Housing Data

housingCaliRooms_df = df_californiaHouse.iloc[18:23, 0:2]
housingTexasRooms_df = df_texasHouse.iloc[18:23, 0:2]
for i in range(18, len(housingCaliRooms_df) + 18):
  if("," in housingCaliRooms_df["2"][i]):
    housingCaliRooms_df["2"][i] = housingCaliRooms_df["2"][i].replace(",", "")
    housingCaliRooms_df["2"][i] = float(housingCaliRooms_df["2"][i])

for i in range(18, len(housingTexasRooms_df) + 18):
  if("," in housingTexasRooms_df["2"][i]):
    housingTexasRooms_df["2"][i] = housingTexasRooms_df["2"][i].replace(",", "")
    housingTexasRooms_df["2"][i] = float(housingTexasRooms_df["2"][i])
housingCaliRooms_df['State'] = 'California'
housingTexasRooms_df['State'] = 'Texas'
rooms = [housingCaliRooms_df, housingTexasRooms_df]
combinedRooms_df = pd.concat(rooms)
roomsBar = px.bar(combinedRooms_df, x = '1', y = '2', color = 'State', barmode = 'group' , labels = {'1':'Room range for Houses Built', '2':'Number of Houses'}, title = 'Range of Rooms within Houses Built (California/Texas)')
print("Bar Chart for Number of Houses with Certain Range of Rooms")
print("")
roomsBar.show()
print("Insights:")
print("1. Both Texas and California have the least amount of houses with 1 room.")
print("2. Texas has more houses with 8 or more rooms than California does.")
print("3. Both California and Texas have the majority of their houses with 4 to 5 rooms.")
print("4. California has a much more significant amount of houses with 4-5 rooms than Texas does.")
print("5. California overall has more houses with various amounts of rooms than Texas does.")
print(" ")

# Education from Race Data

raceCailEducation_df = df_californiaRace.iloc[21:25, 0:2]
for i in range(21, len(raceCailEducation_df) + 21):
  if("," in raceCailEducation_df["2"][i]):
    raceCailEducation_df["2"][i] = raceCailEducation_df["2"][i].replace(",", "")
    raceCailEducation_df["2"][i] = float(raceCailEducation_df["2"][i])

raceTexasEducation_df = df_texasRace.iloc[21:25, 0:2]
for i in range(21, len(raceCailEducation_df) + 21):
  if("," in raceTexasEducation_df["2"][i]):
    raceTexasEducation_df["2"][i] = raceTexasEducation_df["2"][i].replace(",", "")
    raceTexasEducation_df["2"][i] = float(raceTexasEducation_df["2"][i])
raceCailEducation_df['State'] = 'California'
raceTexasEducation_df['State'] = 'Texas'
education = [raceCailEducation_df, raceTexasEducation_df]
combinedEducation_df = pd.concat(education)
educationSunbusrt = px.sunburst(combinedEducation_df, path = ['State', '1'], values = '2')
print("Sunburst Chart of the Education Backgrounds of Homeowners of Texas and California")
print("")
educationSunbusrt.show()
print("Insights:")
print("1. California has more homeowners with a bachelors degree or higher than Texas does.")
print("2. California has more homeowners with a college or associate's degree than Texas does.")
print("3. California has more homeowners with less than a high school degree than Texas does.")
print("4. Texas has more homeowners with a high school degree than California does.")
print("5. California overall has more homeowners who have above a high school degree than Texas does.")
print(" ")

# Age from Race Data

raceCaliAge_df = df_californiaRace.iloc[13:20, 0:2]
for i in range(13, len(raceCaliAge_df) + 13):
  if("," in raceCaliAge_df["2"][i]):
    raceCaliAge_df["2"][i] = raceCaliAge_df["2"][i].replace(",", "")
    raceCaliAge_df["2"][i] = float(raceCaliAge_df["2"][i])

raceTexasAge_df = df_texasRace.iloc[13:20, 0:2]
for i in range(13, len(raceCaliAge_df) + 13):
  if("," in raceTexasAge_df["2"][i]):
    raceTexasAge_df["2"][i] = raceTexasAge_df["2"][i].replace(",", "")
    raceTexasAge_df["2"][i] = float(raceTexasAge_df["2"][i])
raceCaliAge_df['State'] = 'California'
raceTexasAge_df['State'] = 'Texas'
age = [raceCaliAge_df, raceTexasAge_df]
combinedAge_df = pd.concat(age)
ageSunburst = px.sunburst(combinedAge_df, path = ['State', '1'], values = '2')
print("Sunburst Chart of Ages of Homeowners of Texas and California")
print("")
ageSunburst.show()
print("Insights:")
print("1. Texas has slightly more homeowners under the age of 35 than California does.")
print("2. Both Texas and California have a significant low number of homeowners of the age 85 and over.")
print("3. California has more homeowners of the age 35 and above than Texas does.")
print("4. California overall has more homeowners than Texas does.")
print("5. California and Texas both almost have the same number of homeowners within ages 35 and under to 44.")
print(" ")

# Vehicle Data for Housing Aspects

housingCaliVehicles_df = df_californiaHouse.iloc[32:36, 0:2]
housingTexasVehicles_df = df_texasHouse.iloc[32:36, 0:2]
for i in range(32, len(housingCaliVehicles_df) + 32):
  if("," in housingCaliVehicles_df["2"][i]):
    housingCaliVehicles_df["2"][i] = housingCaliVehicles_df["2"][i].replace(",", "")
    housingCaliVehicles_df["2"][i] = float(housingCaliVehicles_df["2"][i])
for i in range(32, len(housingCaliVehicles_df) + 32):
  if("," in housingTexasVehicles_df["2"][i]):
    housingTexasVehicles_df["2"][i] = housingTexasVehicles_df["2"][i].replace(",", "")
    housingTexasVehicles_df["2"][i] = float(housingTexasVehicles_df["2"][i])
housingCaliVehicles_df['State'] = 'California'
housingTexasVehicles_df['State'] = 'Texas'
vehicles = [housingCaliVehicles_df, housingTexasVehicles_df]
combinedVehicles_df = pd.concat(vehicles)
vehiclesBar = px.bar(combinedVehicles_df, x = '1', y = '2', color = 'State', barmode = 'group' , labels = {'1':'Number of Vehicles', '2':'Number of Houses'}, title = 'Number of Vehicles within Households (California/Texas)')
print("Bar Chart of the Number of Vehicles within Households for California and Texas")
print("")
vehiclesBar.show()
print("Insights:")
print("1. California overall has more households with cars than Texas does.")
print("2. Both Texas and California have the majority of their households with 2 vehicles available.")
print("3. Both Texas and California have the least majority of their households with no vehicle available.")
print("4. More than 5 million homeowners from both states have more than 1 vehicle available at their household.")
print("5. Less than 1 million homeowners from both states have no vehicles available at their household.")
print(" ")

# Icicle Chart for Race Data

raceCaliEthnicity_df = df_californiaRace.iloc[3:10, 0:2]
for i in range(3, len(raceCaliEthnicity_df) + 3):
  if("," in raceCaliEthnicity_df["2"][i]):
    raceCaliEthnicity_df["2"][i] = raceCaliEthnicity_df["2"][i].replace(",", "")
    raceCaliEthnicity_df["2"][i] = float(raceCaliEthnicity_df["2"][i])
raceTexasEthnicity_df = df_texasRace.iloc[3:10, 0:2]
for i in range(3, len(raceCaliEthnicity_df) + 3):
  if("," in raceTexasEthnicity_df["2"][i]):
    raceTexasEthnicity_df["2"][i] = raceTexasEthnicity_df["2"][i].replace(",", "")
    raceTexasEthnicity_df["2"][i] = float(raceTexasEthnicity_df["2"][i])
raceCaliEthnicity_df['State'] = 'California'
raceTexasEthnicity_df['State'] = 'Texas'
ethnicity = [raceCaliEthnicity_df, raceTexasEthnicity_df]
combinedEthnicities = pd.concat(ethnicity)
ethnicityIcicle = px.icicle(combinedEthnicities, path = [px.Constant('all'), 'State', '1'], values = '2')
ethnicityIcicle.update_traces(root_color = 'lightgrey')
print("Icicle Chart of the Races of Homeowners in California and Texas")
print("")
ethnicityIcicle.show()
print("Insights:")
print("1. In both states the largest race of home owners was white.")
print("2. For both states the lowest race for amount of home owners was Hawaiian and other Pacific Islanders.")
print("3. A comparatively smaller amount of African Americans owned the total amount of homes in California when compared to Texas.")
print("4. In California, the rest of the races combined had more non-white home owners while, Texas white home owners were over 50%.")
print("5. California has over 2 million more total home owners than Texas.")
print(" ")


# Clean data for histogram chart

raceCaliOwner_df = df_californiaRace.iloc[3:9,0:2]
raceCaliRenter_df = df_californiaRace.iloc[3:9,[0,9]]

for i in range(3, len(raceCaliRenter_df) + 3):
  if("," in raceCaliRenter_df["10"][i]):
    raceCaliRenter_df["10"][i] = raceCaliRenter_df["10"][i].replace(",", "")
    raceCaliRenter_df["10"][i] = float(raceCaliRenter_df["10"][i])

for i in range(3, len(raceCaliOwner_df) + 3):
  if("," in raceCaliOwner_df["1"][i]):
    raceCaliOwner_df["1"][i] = raceCaliOwner_df["1"][i].replace(",", "")
    raceCaliOwner_df["1"][i] = float(raceCaliOwner_df["1"][i])
raceTexasOwner_df = df_texasRace.iloc[3:9,0:2]
raceTexasRenter_df = df_texasRace.iloc[3:9, [0,9]]
for i in range(3, len(raceCaliRenter_df) + 3):
  if("," in raceTexasOwner_df["1"][i]):
    raceTexasOwner_df["1"][i] = raceTexasOwner_df["1"][i].replace(",", "")
    raceTexasOwner_df["1"][i] = float(raceTexasOwner_df["1"][i])
for i in range(3, len(raceTexasRenter_df) + 3):
  if("," in raceTexasRenter_df["10"][i]):
    raceTexasRenter_df["10"][i] = raceTexasRenter_df["10"][i].replace(",", "")
    raceTexasRenter_df["10"][i] = float(raceTexasRenter_df["10"][i])

# Histogram for race between household owners and renters in California and Texas

raceCaliOwner_df['Category'] = 'Owner'
raceCaliRenter_df['Category'] = 'Renter'
raceTexasOwner_df['Category'] = 'Owner'
raceTexasRenter_df['Category'] = 'Renter'
raceCaliRenter_df = raceCaliRenter_df.rename(columns ={'10':'2'})
raceTexasRenter_df = raceTexasRenter_df.rename(columns ={'10':'2'})
combinedCali = [raceCaliOwner_df, raceCaliRenter_df]
combinedTexas = [raceTexasOwner_df, raceTexasRenter_df]
combinedCali_df = pd.concat(combinedCali)
combinedTexas_df = pd.concat(combinedTexas)
combinedCaliHistogram = px.histogram(combinedCali_df,  x ='1', y = '2', color = 'Category', labels = {'1': 'Race', '2':'houses'}, title = "California Home Renters/Owners by Race")
print("Histograms of the Race of Owners and Renters of Households in Texas and California")
print("")
combinedCaliHistogram.show()
combinedTexasHistogram = px.histogram(combinedTexas_df, x = '1', y = '2', color ='Category', labels = {'1': 'Race', '2': 'houses'}, title = "Texas Home Renters/Owners by Race")
combinedTexasHistogram.show()
print("Insights:")
print("1. The largest amount of total homes in renters/owners for both state's races was White. In the majority of cases more people owned than rented their home for both states.")
print("2. In both states, Asians had the largest ratio between owners and renters.")
print("3. In the majority of cases more people owned than rented their home for both states.")
print("4. In Texas, a larger number of African Americans made up homes compared to California, but the opposite is true for Asians. California had a greater number of total amount of homes owned/rented by all races compared to Texas.")
print("5. In California, some other race made up the second largest amount of total homes while in Texas it was African Americans.")
print(" ")


# Pie Charts for Income, Value, and Ratio

percentCali4_df = df_cali.iloc[2:9, [0,2,3]]
percentTexas4_df = df_texas.iloc[2:9, [0, 2, 3]]
percentCaliRatio_df = df_cali.iloc[28:33, [0, 2, 3]]
percentTexasRatio_df = df_texas.iloc[28:33, [0, 2, 3]]
percentCaliIncome_df = df_cali.iloc[18:26, [0, 2, 3]]
percentTexasIncome_df = df_texas.iloc[18:26, [0, 2, 3]]


valueIndex = ['Less than 50k', '50k to 99.99k', '100k to 299.99k', '300k to 499.99k' , '500k to 749.99k', '750k to 999.99k', '1M+']
ratioIndex = ['<= 2.0', '2.0 - 2.9', '3.0 - 3.9', '>= 4.0', 'Not computed']
incomeIndex = ['<= 10k', '10k - 24.99k', '25k - 34.99k', '35k - 49.99k', '50k - 74.99k', '75k - 99.99k', '100k - 149.99k', '>= 150k']

percentCali4_df.index = valueIndex
percentTexas4_df.index = valueIndex
percentCaliRatio_df.index = ratioIndex
percentTexasRatio_df.index = ratioIndex
percentCaliIncome_df.index = incomeIndex
percentTexasIncome_df.index = incomeIndex

caliPie = px.pie(percentCali4_df, values = '4', names = percentCali4_df.index, hover_data = '3', labels = {'4': '%', 'index':'Range', '3':'# of homes'}, title = 'Ranges of House Values in California')
print("Pie Charts of Household Values in California and Texas")
print("")
caliPie.show()
texasPie = px.pie(percentTexas4_df, values = '4', names = percentTexas4_df.index, hover_data = '3', labels = {'4':'%', 'index':'Range', '3':'# of homes'}, title = 'Ranges of House Values in Texas')
texasPie.show()
print("Insights:")
print("1. For the ranges of house mortgage value, California has the highest percentage in houses which are 1M + while Texas is the most between 100k to 299k.")
print("2. The least for California is 50k to 99k while Texas is less than 50k.")
print("3. The category that makes up the highest percentage for California(1M+) is the second smallest percentage for Texas only accounting for less than %2 of the total range of house mortgages.")
print("4. California has only 3 categories combined that make up over 80% while Texas takes 4 different categories.")
print("5. The trend for California is that as the house mortgage range goes up so does the total percentage that it takes up, while in Texas the house mortgage and percentage aren’t as strongly correlated.")
print(" ")


caliPieIncome = px.pie(percentCaliIncome_df, values = '4', names = percentCaliIncome_df.index, hover_data = '3', labels = {'4':'%', 'index':'Range', '3':'# of homes',}, title = 'Ranges of Yearly Income for Homeowners in California')
print("Pie Charts of Household Income Values in California and Texas")
print("")
caliPieIncome.show()
texasPieIncome = px.pie(percentTexasIncome_df, values = '4', names = percentTexasIncome_df.index, hover_data = '3', labels = {'4':'%', 'index':'Range', '3':'# of homes',}, title = 'Ranges of yearly income for Homeowners in Texas')
texasPieIncome.show()
print("Insights:")
print("1. The highest percentage of yearly income for both states is 150k+.")
print("2. The lowest percentage of yearly income for both states is <= 10k.")
print("3. The population for California which makes at least 150k is almost 50% most likely showing that a large percentage of its population is high class.")
print("4. Texas has a lot more variety outside of those making 150k+ meaning they have a larger middle class.")
print("5. For both states the number of people making <50k yearly makes up less than 25% of the pie meaning they have a comparatively small lower class.")
print(" ")


caliPieRatio = px.pie(percentCaliRatio_df, values = '4', names = percentCaliRatio_df.index, hover_data = '3', labels = {'4':'%', 'index':'Range', '3':'# of homes'}, title = 'Ratio of Household Income to House Value (California)')
print("Pie Charts of the Ratio of Household Values to Household Income Values in Texas and California")
print("")
caliPieRatio.show()
texasPieRatio = px.pie(percentTexasRatio_df, values = '4', names = percentTexasRatio_df.index, hover_data = '3', labels = {'4':'%', 'index':'Range', '3':'# of homes'}, title = 'Ratio of Household Income to House Value (Texas)')
texasPieRatio.show()
print("Insights:")
print("1. The highest percentage and majority for the ratio of California is >= 4.0 meaning that nearly 2/3rds of the population own a home that is worth 4x or more of their yearly income.")
print("2. Texas has the highest percentage in <= 2.0.")
print("3. The second largest in Texas is >= 4.0 showing the strong polarity to either side for Texas homeowners (they either own a home that is extremely affordable or extremely unaffordable).")
print("4. There is a relatively even distribution of the ratio in Texas, while California has a majority of homes that are unaffordable to the owner.")
print("5. For California, the higher the ratio, the larger the percentage it took upon the pie chart, while Texas didn’t have much of a correlation.")
print(" ")

# Creating files with visualizations

import plotly.io as pio

fhVizTexas1 = open("pieChartTexasViz1.html", "w")
fhVizCalifornia1 = open("pieChartCaliforniaViz1.html", "w")
fhVizTexas2 = open("pieChartTexasViz2.html", "w")
fhVizCalifornia2 = open("pieChartCaliforniaViz2.html", "w")
fhVizTexas3 = open("pieChartTexasViz3.html", "w")
fhVizCalifornia3 = open("pieChartCaliforniaViz3.html", "w")
fhVizHousesTime4 = open("barChartViz4.html", "w")
fhVizHousesRoom5 = open("barChartViz5.html", "w")
fhVizRaceEducation6 = open("sunBurstViz6.html", "w")
fhVizRaceAges7 = open("sunBurstViz7.html", "w")
fhVizHousesVehicles8 = open("barChartViz8.html", "w")
fhVizRaceEthnicites9 = open("boxChartViz9.html", "w")
fhVizRaceEthnicitiesCalifornia10 = open("histogramCaliforniaViz10.html", "w")
fhVizRaceEthnicitiesTexas10 = open("histogramTexasViz10.html", "w")

fhVizTexas1.close()
fhVizCalifornia1.close()
fhVizTexas2.close()
fhVizCalifornia2.close()
fhVizTexas3.close()
fhVizCalifornia3.close()
fhVizHousesTime4.close()
fhVizHousesRoom5.close()
fhVizRaceEducation6.close()
fhVizRaceAges7.close()
fhVizHousesVehicles8.close()
fhVizRaceEthnicites9.close()
fhVizRaceEthnicitiesCalifornia10.close()
fhVizRaceEthnicitiesTexas10.close()

pio.write_html(texasPie, file = "pieChartTexasViz1.html", auto_open = True, full_html = False)
pio.write_html(caliPie, file = "pieChartCaliforniaViz1.html", auto_open = True, full_html = False)
pio.write_html(texasPieIncome, file = "pieChartTexasViz2.html", auto_open = True, full_html = False)
pio.write_html(caliPieIncome, file = "pieChartCaliforniaViz2.html", auto_open = True, full_html = False)
pio.write_html(texasPieRatio, file = "pieChartTexasViz3.html", auto_open = True, full_html = False)
pio.write_html(caliPieRatio, file = "pieChartCaliforniaViz3.html", auto_open = True, full_html = False)
pio.write_html(yearBuiltBar, file = "barChartViz4.html", auto_open = True, full_html = False)
pio.write_html(roomsBar, file = "barChartViz5.html", auto_open = True, full_html = False)
pio.write_html(educationSunbusrt, file = "sunBurstViz6.html", auto_open = True, full_html = False)
pio.write_html(ageSunburst, file = "sunBurstViz7.html", auto_open = True, full_html = False)
pio.write_html(vehiclesBar, file = "barChartViz8.html", auto_open = True, full_html = False)
pio.write_html(ethnicityIcicle, file = "boxChartViz9.html", auto_open = True, full_html = False)
pio.write_html(combinedCaliHistogram, file = "histogramCaliforniaViz10.html", auto_open = True, full_html = False)
pio.write_html(combinedTexasHistogram, file = "histogramTexasViz10.html", auto_open = True, full_html = False)